### ISSUE TITLE
本地无法正常跑起来

### ISSUE THREAD

**Issue by zhuima** [zhxiaohe/k8sexec#1]
echo对应的路由一直报错，如下
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x159e526]

goroutine 9 [running]:
github.com/gorilla/websocket.(*Conn).NextReader(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/zhuima/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:971 +0x26
github.com/gorilla/websocket.(*Conn).ReadMessage(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/zhuima/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:1064 +0x2f
k8sexec/service.(*WsConnection).readLoop(0xc0003e7ef0)
        /Users/zhuima/code-learn/golang/k8sexec/service/vi.go:30 +0x45
created by k8sexec/service.wsInit
        /Users/zhuima/code-learn/golang/k8sexec/service/vi.go:103 +0x165
exit status 2
103行对应的是
go WS.readLoop()

**Comment by zhxiaohe** [comment]
刚download本地是可以run起来的

**Comment by zhxiaohe** [comment]
刚download本地是可以run起来的

`tar zxf k8sexec-master.zip && cd k8sexec-master`

`go mod tidy`

`go mod vendor`

`修改 conf/k8s.conf`

`修改 service/view.go  下func ExecShell`

       ` podName := "nginx-569bf69fb7-5gr8w"`

	`podNs := "default"`

	`containerName := "nginx"`

`cd cmd && go run main.go`

![image](https://user-images.githubusercontent.com/11907113/165434889-0ae3d18d-154a-4eee-8866-3c8dacf363ee.png)
